theme: jekyll-theme-architect
show_downloads: true
github:
  repository_url: https://github.com/ttlion/sdtDBN_code
  gui_repo_url: https://github.com/ttlion/sdtDBNsGUI
  zip_url: sdtDBN_v0_0_1.jar
  tar_url: sources_sdtDBN_v0_0_1.zip
  gui_url_windows: sdtDBN_GUI_windows.zip
